version: '3.8'

services:
  app:
    build: 
      context: ./portifolio-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  fastapi:
    build:
      context: ./portifolio-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always