version: '3.8'

services:
  app:
    build: 
      context: ./portfolio-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: always


  admin:
    build:
      context: ./portfolio-admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: always

  api:
    build:
      context: ./portfolio-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
