version: '3.8'

services:
  api:
    build:
      context: ./portfolio-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always


  app:
    build: 
      context: ./portfolio-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
