version: '3.8'

services:
  app:
    build: 
      context: ./portfolio-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./portfolio-icons-lib:/app/portfolio-icons-lib 

  api:
    build:
      context: ./portfolio-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always